// Generate the standard per-set product lineup for CURRENT retail-era Pokémon sets (Scarlet & Violet +
// Mega Evolution). The Drops DB carries set-specific collections but is missing the universal core SKUs
// (booster packs, bundles, blisters) for most sets — this fills them with the standard modern MSRPs.
//
// Output: data/pokemon-catalog-supplement.json (a sync-safe curated overlay; drops_db.json stays a pure
// Drops DB snapshot). seedCatalogSupplement() loads it into `products` on boot (insert-if-absent).
//
//   npx tsx scripts/gen-pokemon-catalog.ts
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const sets = JSON.parse(readFileSync(join(here, "../data/pokemon-sets.json"), "utf8")) as
  { eras: Array<{ era: string; sets: Array<{ code: string; name: string; kind?: string; release?: string }> }> };
const drops = JSON.parse(readFileSync(join(here, "../data/drops_db.json"), "utf8")) as
  { products: Array<{ series?: string; type?: string; category?: string }> };

// Current retail eras only — older sets predate ETBs/booster bundles, so applying this taxonomy there
// would fabricate products that never existed. (Owner can extend to Sword & Shield later w/ era pricing.)
const ERAS = new Set(["Mega Evolution", "Scarlet & Violet"]);

// Standard SV/Mega-era retail MSRPs (USD). Set-specific collections keep their own prices from the Drops DB.
const CORE: Array<{ type: string; msrp: number; mainOnly?: boolean }> = [
  { type: "Booster Pack", msrp: 4.49 },
  { type: "Booster Bundle", msrp: 26.94 },
  { type: "Booster Box", msrp: 161.64, mainOnly: true },
  { type: "Single-Pack Blister", msrp: 6.49 },
  { type: "Three-Pack Blister", msrp: 14.99 },
  { type: "Checklane Blister", msrp: 5.99, mainOnly: true },
  { type: "Elite Trainer Box", msrp: 49.99 },
];

const norm = (s: string) => (s || "").toLowerCase().replace(/\s*\(base\)\s*/g, "").replace(/\s*\/\s*/g, " & ").trim();
// Types a set already carries in the Drops DB (so we never duplicate) — matched on normalized series name.
const have = new Map<string, Set<string>>();
for (const p of drops.products) {
  if (p.category !== "Pokémon TCG" || !p.series || !p.type) continue;
  const k = norm(p.series); if (!have.has(k)) have.set(k, new Set());
  have.get(k)!.add(p.type.toLowerCase());
}

const out: Array<Record<string, unknown>> = [];
const summary: string[] = [];
for (const e of sets.eras) {
  if (!ERAS.has(e.era)) continue;
  for (const s of e.sets) {
    const isMain = (s.kind || "main") !== "special";
    const existing = have.get(norm(s.name)) || new Set<string>();
    const added: string[] = [];
    for (const core of CORE) {
      if (core.mainOnly && !isMain) continue;
      // treat "ETB" and "Elite Trainer Box" as the same; likewise the blister variants
      const aliases = core.type === "Elite Trainer Box" ? ["elite trainer box", "etb"]
        : core.type === "Three-Pack Blister" ? ["three-pack blister", "3-pack blister", "3-pack"]
        : core.type === "Single-Pack Blister" ? ["single-pack blister", "1-pack blister", "blister"]
        : [core.type.toLowerCase()];
      if (aliases.some((a) => existing.has(a))) continue;
      out.push({
        id: `pk-supp-${String(s.code).toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${core.type.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
        category: "Pokémon TCG",
        series: s.name,
        type: core.type,
        title: `${s.name} ${core.type}`,
        pmsrp: core.msrp,
        language: "English",
      });
      added.push(core.type);
    }
    if (added.length) summary.push(`  ${s.code.padEnd(9)} ${s.name.slice(0, 26).padEnd(26)} ${isMain ? "main   " : "special"} +${added.length}: ${added.join(", ")}`);
  }
}

writeFileSync(join(here, "../data/pokemon-catalog-supplement.json"),
  JSON.stringify({ _note: "Curated core-SKU overlay for current-era Pokémon sets; generated by scripts/gen-pokemon-catalog.ts. Sync-safe (not overwritten by sync-dropsdb).", cats: ["Pokémon TCG"], products: out }, null, 2) + "\n");
console.log(`Generated ${out.length} supplement products across current-era sets:\n${summary.join("\n")}`);
