#!/usr/bin/env node
// gen-index.mjs — builds docs/design/INDEX.md, the section index for the giant HTML files
// (checkit.html 888K, app.html 534K, comps up to 1.7M). Agents NEVER open these files whole:
// read INDEX.md, find your section, then read ONLY that line range.
// Auto-regenerated by a PostToolUse hook whenever a source file changes. Do not hand-edit INDEX.md.
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";

const OUT = "docs/design/INDEX.md";
const sources = ["public/checkit.html", "public/app.html"];
const compsDir = "docs/design/comps";
if (existsSync(compsDir)) {
  for (const f of readdirSync(compsDir).sort()) {
    if (f.endsWith(".html")) sources.push(join(compsDir, f));
  }
}

const stripTags = (s) => s.replace(/<[^>]*>/g, "").replace(/\s+/g, " ").trim();

function indexFile(path) {
  const lines = readFileSync(path, "utf8").split("\n");
  const entries = [];
  const idRe = /<([a-z][a-z0-9]*)\b([^>]*?)\sid="([\w][\w-]*)"/g;
  lines.forEach((line, i) => {
    for (const m of line.matchAll(idRe)) {
      const [, tag, attrs, id] = m;
      const cls = (attrs.match(/class="([^"]+)"/) || [])[1] || "";
      // Description: a heading on this or the next 3 lines wins; else an aria-label on the element.
      let desc = "";
      for (let j = i; j < Math.min(i + 4, lines.length) && !desc; j++) {
        const h = lines[j].match(/<h[1-6][^>]*>(.*?)<\/h[1-6]>/);
        if (h) desc = stripTags(h[1]);
      }
      if (!desc) desc = (attrs.match(/aria-label="([^"]+)"/) || [])[1] || "";
      const el = tag + (cls ? "." + cls.trim().split(/\s+/).slice(0, 2).join(".") : "");
      entries.push({ id, el, line: i + 1, desc: desc.slice(0, 80) });
    }
  });
  // End line = the line before the next id in the file (a NAVIGATION range, not exact DOM bounds).
  for (let k = 0; k < entries.length; k++) {
    const next = entries.slice(k + 1).find((e) => e.line > entries[k].line);
    entries[k].end = next ? next.line - 1 : lines.length;
  }
  return { path, total: lines.length, entries };
}

const indexed = sources.filter((p) => existsSync(p)).map(indexFile);
const md = [
  "# design/INDEX.md — the section index (GENERATED — do not hand-edit)",
  "",
  "Built by `node scripts/gen-index.mjs`; a hook regenerates it when a source file changes.",
  "**The law: NEVER open these files whole.** Find your section here, then Read ONLY the line",
  "range (`offset` + `limit`). Ranges run to the next `id=` — a navigation aid, not exact DOM bounds.",
  "",
];
for (const f of indexed) {
  md.push(`## ${f.path} (${f.total} lines, ${f.entries.length} sections)`, "");
  md.push("| id | element | lines | description |", "|---|---|---|---|");
  for (const e of f.entries) {
    md.push(`| ${e.id} | ${e.el} | ${e.line}–${e.end} | ${e.desc.replace(/\|/g, "\\|")} |`);
  }
  md.push("");
}
writeFileSync(OUT, md.join("\n") + "\n");
console.log(`INDEX.md: ${indexed.map((f) => `${f.path} ${f.entries.length}`).join(" · ")}`);
